### ISSUE TITLE
Panic while writing on the HID device

### ISSUE THREAD

**Issue by alexdupre** [trezor/trezord-go#7]
Full trezord-log after opening beta-wallet.trezor.io with Firefox on FreeBSD.

```
2018/02/09 12:45:45 POST /
127.0.0.1 - - [09/Feb/2018:12:45:45 +0100] "POST / HTTP/1.1" 200 20
2018/02/09 12:45:45 POST /enumerate
127.0.0.1 - - [09/Feb/2018:12:45:45 +0100] "POST /enumerate HTTP/1.1" 200 123
2018/02/09 12:45:46 POST /listen
2018/02/09 12:45:46 POST /acquire/hid504e0c8fe6cd83ce6ca39c62602ce5786f28bfa3a0b2110e5d106128ad952cef/null
127.0.0.1 - - [09/Feb/2018:12:45:46 +0100] "POST /acquire/hid504e0c8fe6cd83ce6ca39c62602ce5786f28bfa3a0b2110e5d106128ad952cef/null HTTP/1.1" 200 16
2018/02/09 12:45:46 POST /call/1
2018/02/09 12:45:46 http: panic serving 127.0.0.1:33546: runtime error: invalid memory address or nil pointer dereference
goroutine 37 [running]:
net/http.(*conn).serve.func1(0xc4200afd60)
        /usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x6cbca0, 0xa88f90)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/trezor/trezord-go/usb.(*HID).readWrite(0xc420090148, 0xc42012e700, 0x40, 0x40, 0x0, 0x6bbfa0, 0x6e0701, 0xc42012e700)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/usb/hidapi.go:92 +0x7e
github.com/trezor/trezord-go/usb.(*HID).Write(0xc420090148, 0xc42012e700, 0x40, 0x40, 0x0, 0x800b39208, 0xc4200557f0)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/usb/hidapi.go:99 +0x4e
github.com/trezor/trezord-go/wire.(*Message).WriteTo(0xc42010cb60, 0x800b39208, 0xc420090148, 0x800b39208, 0xc420090148, 0xc420092280)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/wire/v1.go:53 +0x1e1
github.com/trezor/trezord-go/server.(*server).Call(0xc420092280, 0x800b39120, 0xc4201941e0, 0xc42013a800)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/server/http.go:398 +0x2e3
github.com/trezor/trezord-go/server.(*server).Call-fm(0x800b39120, 0xc4201941e0, 0xc42013a800)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/server/http.go:63 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4200810a0, 0x800b39120, 0xc4201941e0, 0xc42013a800)
        /usr/local/go/src/net/http/server.go:1918 +0x44
github.com/trezor/trezord-go/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200aa240, 0x800b39120, 0xc4201941e0, 0xc42013a800)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/vendor/github.com/gorilla/mux/mux.go:150 +0xed
github.com/trezor/trezord-go/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc4201307e0, 0x800b39120, 0xc4201941e0, 0xc42013a600)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/vendor/github.com/gorilla/handlers/cors.go:128 +0x20b
github.com/trezor/trezord-go/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xa944a0, 0xc420090010, 0xa93ae0, 0xc4201307e0, 0xa984e0, 0xc42013c1c0, 0xc42013a600)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/vendor/github.com/gorilla/handlers/handlers.go:69 +0x123
github.com/trezor/trezord-go/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc42010c900, 0xa984e0, 0xc42013c1c0, 0xc42013a600)
        <autogenerated>:1 +0x75
github.com/trezor/trezord-go/server.logRequest.func1(0xa984e0, 0xc42013c1c0, 0xc42013a600)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/server/http.go:88 +0x108
net/http.HandlerFunc.ServeHTTP(0xc42010c920, 0xa984e0, 0xc42013c1c0, 0xc42013a600)
        /usr/local/go/src/net/http/server.go:1918 +0x44
net/http.serverHandler.ServeHTTP(0xc4200a8ea0, 0xa984e0, 0xc42013c1c0, 0xc42013a600)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4200afd60, 0xa98a60, 0xc42009e640)
        /usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x288
2018/02/09 12:45:46 POST /call/1
2018/02/09 12:45:46 http: panic serving 127.0.0.1:33547: runtime error: invalid memory address or nil pointer dereference
goroutine 41 [running]:
net/http.(*conn).serve.func1(0xc4200afea0)
        /usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x6cbca0, 0xa88f90)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/trezor/trezord-go/usb.(*HID).readWrite(0xc420090148, 0xc42012e780, 0x40, 0x40, 0x0, 0x6bbfa0, 0x6e0701, 0xc42012e780)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/usb/hidapi.go:92 +0x7e
github.com/trezor/trezord-go/usb.(*HID).Write(0xc420090148, 0xc42012e780, 0x40, 0x40, 0x0, 0x0, 0xc4200557f0)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/usb/hidapi.go:99 +0x4e
github.com/trezor/trezord-go/wire.(*Message).WriteTo(0xc42010cc00, 0x800b39208, 0xc420090148, 0x800b39208, 0xc420090148, 0xc420092280)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/wire/v1.go:53 +0x1e1
github.com/trezor/trezord-go/server.(*server).Call(0xc420092280, 0x800b39120, 0xc420194450, 0xc42013ab00)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/server/http.go:398 +0x2e3
github.com/trezor/trezord-go/server.(*server).Call-fm(0x800b39120, 0xc420194450, 0xc42013ab00)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/server/http.go:63 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4200810a0, 0x800b39120, 0xc420194450, 0xc42013ab00)
        /usr/local/go/src/net/http/server.go:1918 +0x44
github.com/trezor/trezord-go/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200aa240, 0x800b39120, 0xc420194450, 0xc42013ab00)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/vendor/github.com/gorilla/mux/mux.go:150 +0xed
github.com/trezor/trezord-go/vendor/github.com/gorilla/handlers.(*cors).ServeHTTP(0xc4201307e0, 0x800b39120, 0xc420194450, 0xc42013a900)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/vendor/github.com/gorilla/handlers/cors.go:128 +0x20b
github.com/trezor/trezord-go/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0xa944a0, 0xc420090010, 0xa93ae0, 0xc4201307e0, 0xa984e0, 0xc42013c460, 0xc42013a900)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/vendor/github.com/gorilla/handlers/handlers.go:69 +0x123
github.com/trezor/trezord-go/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc42010c900, 0xa984e0, 0xc42013c460, 0xc42013a900)
        <autogenerated>:1 +0x75
github.com/trezor/trezord-go/server.logRequest.func1(0xa984e0, 0xc42013c460, 0xc42013a900)
        /wrkdirs/usr/ports/security/trezord-go/work/src/github.com/trezor/trezord-go/server/http.go:88 +0x108
net/http.HandlerFunc.ServeHTTP(0xc42010c920, 0xa984e0, 0xc42013c460, 0xc42013a900)
        /usr/local/go/src/net/http/server.go:1918 +0x44
net/http.serverHandler.ServeHTTP(0xc4200a8ea0, 0xa984e0, 0xc42013c460, 0xc42013a900)
        /usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc4200afea0, 0xa98a60, 0xc42009e880)
        /usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2720 +0x288
2018/02/09 12:45:46 POST /release/1
127.0.0.1 - - [09/Feb/2018:12:45:46 +0100] "POST /release/1 HTTP/1.1" 200 16
```

**Comment by karel-3d** [comment]
Yes. I realized it's an issue and force-pushed it (so bisect works later)

**Comment by alexdupre** [comment]
I confirm the issue has been fixed (even if the hidapi backend continues to not work reliably on FreeBSD, but that's not important since we use libusb backend)
